name: oauth-ora-hydra-dev

services:
  # OAuth2 Server (Ory Hydra)
  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/hydra
      - hydra-sqlite:/var/lib/sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - SECRETS_SYSTEM=${SECRETS_SYSTEM:-this_needs_to_be_the_same_always_and_also_very_$3cuR3-._}
      - SECRETS_COOKIE=${SECRETS_COOKIE:-this_needs_to_be_the_same_always_and_also_very_$3cuR3-._}
      - URLS_SELF_ISSUER=http://localhost:4444/
      - URLS_CONSENT=http://localhost:3000/consent
      - URLS_LOGIN=http://localhost:3000/login
      - URLS_LOGOUT=http://localhost:3000/logout
      - URLS_ERROR=http://localhost:3000/error
      - URLS_POST_LOGOUT_REDIRECT=http://localhost:3000/
      - LOG_LEVEL=debug
      - LOG_LEAK_SENSITIVE_VALUES=true
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - oauth-network

  # Migration service
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/hydra
      - hydra-sqlite:/var/lib/sqlite
    restart: on-failure
    networks:
      - oauth-network

  # Sample Login & Consent App
  consent-app:
    image: oryd/hydra-login-consent-node:v2.2.0
    ports:
      - "3000:3000"
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
    networks:
      - oauth-network

  # Optional: PostgreSQL (comment out sqlite above and uncomment this for production)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_USER=hydra
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_DB=hydra
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - oauth-network

volumes:
  hydra-sqlite:
  # postgres-data:

networks:
  oauth-network:
    driver: bridge
